import type { Metadata, Viewport } from "next";
import { Box, Flex } from "@chakra-ui/react";
import { Provider } from "@/components/ui/provider";
import { BottomNavBar } from "@/components/BottomNavbar";
import "@/lib/styles/globals.css";
import { TelegramTheme } from "@/components/Telegram";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#FFFFFF",
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script src="https://telegram.org/js/telegram-web-app.js" async />
      </head>
      <body>
        <TelegramTheme>
          <Provider>
            <Box bgColor="background.secondary">
              <Flex justifyContent="center">
                <Box w="full" h="ful" maxW="800px">
                  {children}
                </Box>
                <BottomNavBar />
              </Flex>
            </Box>
          </Provider>
        </TelegramTheme>
      </body>
    </html>
  );
};

export default RootLayout;
